# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

# services 定义容器列表
services:
  user-cli:
    build: ./user-cli
    tty: true
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd:2379"
    depends_on: 
      - user
      - etcd
  user:
    build: ./user
    restart: always
    ports:
      - 60051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd:2379"
      # MICRO_LOG_LEVEL: "debug"
      DB_DRIVER: "postgres"
      DB_URL: "host=database port=5432 user=postgres dbname=bookstore password=mypasswd sslmode=disable"
    depends_on:
      - database
      - etcd
  database:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "mypasswd"
  etcd:
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      # - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
  # datastore:
  #   image: mongo
