# docker-compose.yaml

version: '3.1'

# services
services:
  user-cli:
    build: ./user-cli
    tty: true
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd:2379"
    depends_on:
      - user
      - etcd
  user-api:
    build: ./user-api
    restart: always
    ports: 
      - 8080:80
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd:2379"
      PORT: 80
      GIN_MODE: debug
    depends_on:
      - user
      - etcd
  user:
    build: ./user
    restart: always
    ports:
      - 60051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd:2379"
      # MICRO_LOG_LEVEL: "debug"
      DB_DRIVER: "postgres"
      DB_URL: "host=database port=5432 user=postgres dbname=bookstore password=mypasswd sslmode=disable"
    depends_on:
      - database
      - etcd
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypasswd
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: bookstore
    volumes:
      - ./user/data:/var/lib/postgresql/data/pgdata
  etcd:
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      # - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
  # datastore:
  #   image: mongo
